#!/usr/bin/env bash
#Install nginx web server
sudo apt-get update
sudo apt-get install nginx
sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

# Testing Nginx configurations for Syntax errors
sudo nginx -t

# Restarting Nginx
sudo service nginx reload
