#!/usr/bin/env bash
# This script is displaying loops from 1 to 10
i=0; while ((i++<10)); do if [[ $i -eq 8 ]]; then echo "good luck"; elif [[ $i -eq 4 ]]; then echo "bad luck"; else echo "Best School"; fi;done
